# https://taskfile.dev

version: '3'

vars:
  GREETING: Game!
  GEN_PLUS: open -a "genesis plus"
  BLASTEM: /opt/toolchains/blastem/blastem
  EMU: "{{ .BLASTEM }}"

tasks:
  default:
    cmds:
      - cowsay "{{.GREETING}}"
      - task build
    silent: true

  assets:
    cmds:
      - cowsay "Processing assets..."
      - python3 res/color-snapper.py res/src/player.png res/player.png
      - python3 res/color-snapper.py res/src/popcorn-enemy.png res/popcorn-enemy.png
      - python3 res/color-snapper.py res/src/projectile.png res/projectile.png
    silent: true

  build:
    cmds:
      - source /opt/toolchains/mars/mars.sh
      - make
    silent: true

  clean:
    cmds:
      - make clean
    silent: true
    aliases:
      - clear

  run:
    cmds:
      # runs with "genesis plus"
      - cowsay "Running {{.GREETING}}..."
      # - open -a "Genesis Plus" out/rom.bin
      - "{{ .EMU }} out/rom.bin"
    silent: true

  dev:
    cmds:
      - task clean
      - task build
      - task run
    silent: true
